# This workflow will build a package using Maven and then publish it to GitHub packages on each push to master
# This is based on https://github.com/actions/setup-java#apache-maven-with-a-settings-path
# Determine if we should add a trigger on.release.types: [created] and how this will interact with on push

name: Build-Test PRs

on:
  pull_request:
    branches: ['master']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # This checks out the code

    - uses: actions/cache@v1  # This sets up caching of Maven dependencies to speed up build times
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml
